Test-azure-service-bus/TestWebRole/Models/CustomMessage.cs
namespace TestWebRole.Models
{
    public class CustomMessage
    {
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
    }
}

Test-azure-service-bus/TestWebRole/Models/ReturnCreated.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TestWebRole.Models
{
    public enum ReturnMethod
    {
        DropOff = 0,
        Collection = 1
    }
    public class ReturnCreated
    {
        [Required]
        public string ReturnReference { get; set; }
        [Required]
        public string OrderReference { get; set; }
        [Required]
        public string CustomerId { get; set; }
        [Required]
        public int ReturnMethod { get; set; }
        public DateTime Timestamp { get; set; }
    }
}

Test-azure-service-bus/TestWebRole/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using TestWebRole.Models;
using Microsoft.ServiceBus.Messaging;
using TestWebRole.Connector;

namespace TestWebRole.Controllers
{
    public class HomeController : Controller
    {
        public HomeController()
        {
            QueueConnector.Initialize();
        }
        public ActionResult Index()
        {
            try
            {
                // Get a NamespaceManager which allows you to perform management and
                // diagnostic operations on your Service Bus queues.
                var namespaceManager = QueueConnector.CreateNamespaceManager();

                // Get the queue, and obtain the message count.
                var queue = namespaceManager.GetQueue(QueueConnector.QueueName);
                ViewBag.MessageCount = queue.MessageCount;
            }
            catch (Exception e)
            {
                ViewBag.Result = "Error: " + e.Message;
                ViewBag.MessageCount = 0;
            }
            return View();
        }

        [HttpPost]
        public ActionResult Index(CustomMessage custMessage)
        {
            if (!ModelState.IsValid)
                return View(custMessage);

            // Create a message from the custMessage.
            var message = new BrokeredMessage(custMessage);

            try
            {
                // Submit the custMessage.
                QueueConnector.MessagesQueueClient.Send(message);
                TempData["Result"] = "Message sent successfully.";
            }
            catch (Exception e)
            {
                TempData["Result"] = "Error: " + e.Message;
            }

            return RedirectToAction("Index");

        }

        public ActionResult Process()
        {
            var connectionString =
                "Endpoint=sb://iqanstest1.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=kACru3WDbVWYmD5GEFF81sLIsgi+eyR9fjeO6+NWYpY=";
            var queueName = "MessagesQueue";
            var list = new List<string>();
            var client = QueueClient.CreateFromConnectionString(connectionString, queueName);

            client.OnMessage(message =>
            {
                try
                {
                    list.Add(string.Format("Message id: {0}", message.MessageId));
                    var msg = message.GetBody<CustomMessage>();
                    list.Add("CustomerId: " + msg.CustomerId);
                    list.Add("Name: " + msg.Name);
                    list.Add("Message: " + msg.Message);
                    TempData["Output"] = list;
                    message.Complete();
                    client.Close();
                }
                catch (Exception e)
                {
                    TempData["Err"] = "Error: " + e.Message;
                    message.Abandon();
                }

            }); TempData["Output"] = list;

            return RedirectToAction("Index");
        }
    }
}

Test-azure-service-bus/TestWebRole/Controllers/ReturnsController.cs
using System;
using System.Web.Mvc;
using Microsoft.ServiceBus.Messaging;
using TestWebRole.Connector;
using TestWebRole.Models;
using Newtonsoft.Json;

namespace TestWebRole.Controllers
{
    public class ReturnsController : Controller
    {
        private readonly CustomQueueConnector _connector;
        public ReturnsController()
        {
            _connector = new CustomQueueConnector("ReturnsQueue", "ReturnCreatedTopic","ReturnCreatedSub");
            _connector.Initialize();
        }

        public ActionResult Send()
        {
            try
            {
                var namespaceManager = _connector.CreateNamespaceManager();

                var queue = namespaceManager.GetQueue(_connector.QueueName);
                var sub = namespaceManager.GetSubscription(_connector.TopicName, _connector.SubName);
                ViewBag.MessageCount = queue.MessageCount + "... And Topic(ReturnCreatedTopic) -> Sub (ReturnCreatedSub) Count: " + sub.MessageCountDetails.ActiveMessageCount;
                ViewBag.QueueName = _connector.QueueName;
            }
            catch (Exception e)
            {
                ViewBag.Error = "Error connecting to the Service Bus. Error : " + e.Message;
            }
            return View();
        }

        [HttpPost]
        public ActionResult Send(ReturnCreated msg, bool isTopic)
        {
            if (!ModelState.IsValid)
                return View(msg);

            msg.Timestamp = DateTime.Now;

            if (isTopic)
            {
                try
                {
                    var client = _connector.TopicClient;
                    var message = new BrokeredMessage(msg);
                    message.Properties["msgType"] = message.GetType().AssemblyQualifiedName;
                    client.Send(message);
                    TempData["Result"] = "Message sent successfully. (" + message.MessageId + ")";
                }
                catch (Exception e)
                {
                    TempData["Result"] = "Error: " + e.Message;
                }
            }
            else
            {
                var jsonMsg = JsonConvert.SerializeObject(msg, Formatting.Indented);
                var message = new BrokeredMessage(jsonMsg);

                try
                {
                    // Submit the custMessage.
                    _connector.MessagesQueueClient.Send(message);
                    TempData["Result"] = "Message sent successfully. (" + message.MessageId + ")";
                    TempData["Out"] = jsonMsg;
                }
                catch (Exception e)
                {
                    TempData["Result"] = "Error: " + e.Message;
                }
            }
            return RedirectToAction("Send");
        }
    }
}

Test-azure-service-bus/TestWebRole/Views/Home/Index.cshtml
@model TestWebRole.Models.CustomMessage

@{
    ViewBag.Title = "Index";
}

<style>
    .count-span {
        display: inline-block;
        background: #666;
        color: #fff
    }
</style>
<h2>Index</h2>
<div class="row">
    <div class="col-md-6">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <h4>Send Message</h4>
                <hr />
                @if (TempData["Result"] != null)
                {
                    <p>
                        @TempData["Result"].ToString()
                    </p>
                }
                <p>
                    Total messages in queue to be proccessed: <span class="count-span">@ViewBag.MessageCount</span>
                </p>
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Send" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-6">
        <div class="form-horizontal">
            <p>
                <a href="@Url.Action("Process", "Home")" class="btn btn-primary">Process Now</a>
            </p>
            <p>
                <b>Proccessing output:</b>
            </p>
            @if (TempData["Err"] != null)
            {

            }
            @if (TempData["Output"] != null)
            {
                <ul>
                    @foreach (var op in (List<string>)TempData["Output"])
                    {
                        <li>@op</li>
                    }
                </ul>
            }
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Test-azure-service-bus/TestWebRole/Views/Returns/Send.cshtml
@model TestWebRole.Models.ReturnCreated

@{
    ViewBag.Title = "Send";
}

<h2>Send Return Created Message</h2>

@if (ViewBag.Error != null)
{
    <p class="text-danger">
        @ViewBag.Error
    </p>
}
<div class="row">
    <div class="col-md-8">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <p>
                    Total messages in queue <b>"@ViewBag.QueueName"</b>: @ViewBag.MessageCount
                </p>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                
                <div class="form-group">
                    @Html.LabelFor(model => model.ReturnReference, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.ReturnReference, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReturnReference, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.OrderReference, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.OrderReference, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.OrderReference, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CustomerId, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.EditorFor(model => model.CustomerId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ReturnMethod, htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.DropDownListFor(model => model.ReturnMethod,
                            new List<SelectListItem>
                            {
                                new SelectListItem
                                {
                                    Text = "DropOff", Value = "0" , Selected = true
                                },
                                new SelectListItem
                                {
                                    Text = "Collection", Value = "1"
                                }
                            },
                            new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ReturnMethod, "", new { @class = "text-danger" })
                    </div>
                </div>
                
                <div class="form-group">
                    @Html.Label("Send to a Topic?", htmlAttributes: new { @class = "control-label col-md-3" })
                    <div class="col-md-9">
                        @Html.CheckBox("IsTopic",
                            new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-3 col-md-9">
                        <input type="submit" value="Send" class="btn btn-default" />
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-4">
        <div class="form-horizontal">
            <p style="font-weight: bold">Output:</p>
            <hr />
            @if (TempData["Result"] != null)
            {
                <div>
                    <div>
                        <p>
                            @TempData["Result"].ToString()
                        </p>
                    </div>
                    @if (TempData["Out"] != null)
                    {
                        <div>
                            @Html.Raw(TempData["Out"])
                        </div>
                    }
                </div>
            }
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Test-azure-service-bus/TestWebRole/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Test ASB - WebRole</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Test ASB - WebRole", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Return Created Event", "Send", "Returns")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Iqan's Apps</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>